### ISSUE TITLE
is JavaPhoenixChannels production ready?

### ISSUE THREAD

**Issue by AshwinMekala** [eoinsha/JavaPhoenixChannels#29]
I wan't to create an android app with JavaPhoenixChannels. Before that I wan't to know whether  JavaPhoenixChannels is production ready?

**Comment by eoinsha** [comment]
It's difficult for me to say. I haven't personally put anything into production with JavaPhoenixChannels but I believe others have. Maybe they can comment here. It can do with more attention and more contributors since I'm not regularly maintaining it. It would benefit from better automated test coverage and there is plenty of room for improvement. Anyone is welcome to contribute in any way to help in this improvement.

Whether your app, built with JavaPhoenixChannels, is production ready will ultimately depend on your requirements and how the library is integrated so that is something for you to evaluate.
